# Generated by Django 5.1.3 on 2024-12-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('naem', models.CharField(max_length=100)),
            ],
        ),
    ]
