# Generated by Django 5.1.3 on 2024-12-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='naem',
            new_name='name',
        ),
    ]
